### ISSUE TITLE
Settings for DM`s

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Livia#33]
Please add settings for DMs. Like settings for guids but for DM`s. 
I think best solution is writing to DB id of user and JSON of settings.
Thank you very much for this good framework.

**Comment by CharlotteDunois** [comment]
Is there any reason why you did not use the feature request issue template? One would think that if you don't use the bug or feature request template, your issue is not a bug or feature request. But this is a feature request.

Although "DM settings" are not directly supported, you can indirectly implement it yourself by using the `global` settings as a holder for your DM settings. I don't really see any use cases for "DM settings", DMs don't have any prefix (although you *can* use the global one, commands work without the prefix).

If it's still a concern for you, please edit your issue, use the feature request template and reopen the issue.

**Comment by Nereg** [comment]
Ok thanks.
