### ISSUE TITLE
How to exit correctly ?

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Livia#37]
Hello ! I just noticed that when I closes bot via Ctrl+C bot is online for some time. But in that time bot can't respond to messages. It's unacceptable. Can I fix this ?

**Comment by CharlotteDunois** [comment]
You have to properly disconnect from Discord in order to get don't get this. If you just close the process, your gateway connection is ended abruptly and Discord waits for you to reconnect and uphold the session of your bot for some time, during this time your bot is still shown with the same status.

Use `Client::destroy` to properly close the connection. Please note that the loop should stop automatically, if you close all other connections and timers you added properly.

**Comment by Nereg** [comment]
Thank you !
